name: Deploy project to Maven Central
on:
  release:
    types:
    - created
jobs:
   publish:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-java@v1
         with:
           java-version: 11
           server-id: ossrh
           server-username: MAVEN_USERNAME
           server-password: MAVEN_PASSWORD
      -  id: install-secret-key
         run: |
           export GPG_TTY=$(tty)
           cat <(echo -e "${{ secrets.GPG_SECRET }}") | gpg --batch --import
           gpg --list-secret-keys --keyid-format LONG
      -  name: Publish package
         run: mvn --batch-mode deploy -DskipTests -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -Drevision=${GITHUB_REF##*/} -Dchangelist=
         env:
           MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
           MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}