name: Deploy project to Maven Central
on:
  release:
    types:
    - created
jobs:
   publish:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-java@v1
         with:
           java-version: 11
           server-id: ossrh
           server-username: MAVEN_USERNAME
           server-password: MAVEN_PASSWORD
      -  name: Import GPG key
         id: import_gpg
         uses: crazy-max/ghaction-import-gpg@v3
         with:
           gpg-private-key: ${{ secrets.GPG_SECRET }}
           passphrase: ${{ secrets.GPG_PASSPHRASE }}
      -  name: Publish package
         run: mvn --batch-mode deploy -DskipTests -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -Drevision=1.0.0 -Dchangelist=
         env:
           MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
           MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
